/* tslint:disable */
/* eslint-disable */
/**
 * Schmeconomics.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccountModel,
  ToggleUserToAccountRequest,
  UpdateAccountRequest,
} from '../models/index';
import {
    AccountModelFromJSON,
    AccountModelToJSON,
    ToggleUserToAccountRequestFromJSON,
    ToggleUserToAccountRequestToJSON,
    UpdateAccountRequestFromJSON,
    UpdateAccountRequestToJSON,
} from '../models/index';

export interface AccountCreatePostRequest {
    name?: string;
}

export interface AccountDeleteIdDeleteRequest {
    id: string;
}

export interface AccountToggleUserPostRequest {
    toggleUserToAccountRequest: ToggleUserToAccountRequest;
}

export interface AccountUpdateIdPutRequest {
    id: string;
    updateAccountRequest: UpdateAccountRequest;
}

/**
 * 
 */
export class AccountApi extends runtime.BaseAPI {

    /**
     */
    async accountAllGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AccountModel>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/Account/All`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AccountModelFromJSON));
    }

    /**
     */
    async accountAllGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AccountModel>> {
        const response = await this.accountAllGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async accountCreatePostRaw(requestParameters: AccountCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountModel>> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/Account/Create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountModelFromJSON(jsonValue));
    }

    /**
     */
    async accountCreatePost(requestParameters: AccountCreatePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountModel> {
        const response = await this.accountCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async accountDeleteIdDeleteRaw(requestParameters: AccountDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling accountDeleteIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/Account/Delete/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async accountDeleteIdDelete(requestParameters: AccountDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.accountDeleteIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async accountToggleUserPostRaw(requestParameters: AccountToggleUserPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['toggleUserToAccountRequest'] == null) {
            throw new runtime.RequiredError(
                'toggleUserToAccountRequest',
                'Required parameter "toggleUserToAccountRequest" was null or undefined when calling accountToggleUserPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/Account/ToggleUser`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ToggleUserToAccountRequestToJSON(requestParameters['toggleUserToAccountRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async accountToggleUserPost(requestParameters: AccountToggleUserPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.accountToggleUserPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async accountUpdateIdPutRaw(requestParameters: AccountUpdateIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountModel>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling accountUpdateIdPut().'
            );
        }

        if (requestParameters['updateAccountRequest'] == null) {
            throw new runtime.RequiredError(
                'updateAccountRequest',
                'Required parameter "updateAccountRequest" was null or undefined when calling accountUpdateIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/Account/Update/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAccountRequestToJSON(requestParameters['updateAccountRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountModelFromJSON(jsonValue));
    }

    /**
     */
    async accountUpdateIdPut(requestParameters: AccountUpdateIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountModel> {
        const response = await this.accountUpdateIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
