/* tslint:disable */
/* eslint-disable */
/**
 * Schmeconomics.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SignInModel,
  SignInRequest,
} from '../models/index';
import {
    SignInModelFromJSON,
    SignInModelToJSON,
    SignInRequestFromJSON,
    SignInRequestToJSON,
} from '../models/index';

export interface AuthSignInPostRequest {
    signInRequest: SignInRequest;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     */
    async authRefreshPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignInModel>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/Auth/Refresh`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SignInModelFromJSON(jsonValue));
    }

    /**
     */
    async authRefreshPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignInModel> {
        const response = await this.authRefreshPostRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async authSignInPostRaw(requestParameters: AuthSignInPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignInModel>> {
        if (requestParameters['signInRequest'] == null) {
            throw new runtime.RequiredError(
                'signInRequest',
                'Required parameter "signInRequest" was null or undefined when calling authSignInPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/Auth/SignIn`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SignInRequestToJSON(requestParameters['signInRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SignInModelFromJSON(jsonValue));
    }

    /**
     */
    async authSignInPost(requestParameters: AuthSignInPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignInModel> {
        const response = await this.authSignInPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async authSignOutPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/Auth/SignOut`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async authSignOutPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authSignOutPostRaw(initOverrides);
    }

}
