/* tslint:disable */
/* eslint-disable */
/**
 * Schmeconomics.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CategoryModel,
  CreateCategoryRequest,
  UpdateCategoriesOrderRequest,
  UpdateCategoriesRefillValueRequest,
  UpdateCategoryRequest,
} from '../models/index';
import {
    CategoryModelFromJSON,
    CategoryModelToJSON,
    CreateCategoryRequestFromJSON,
    CreateCategoryRequestToJSON,
    UpdateCategoriesOrderRequestFromJSON,
    UpdateCategoriesOrderRequestToJSON,
    UpdateCategoriesRefillValueRequestFromJSON,
    UpdateCategoriesRefillValueRequestToJSON,
    UpdateCategoryRequestFromJSON,
    UpdateCategoryRequestToJSON,
} from '../models/index';

export interface CategoryCreatePostRequest {
    createCategoryRequest: CreateCategoryRequest;
}

export interface CategoryDeleteIdDeleteRequest {
    id: string;
}

export interface CategoryForAccountAccountIdGetRequest {
    accountId: string;
}

export interface CategoryUpdateIdPutRequest {
    id: string;
    updateCategoryRequest: UpdateCategoryRequest;
}

export interface CategoryUpdateOrderPutRequest {
    updateCategoriesOrderRequest: UpdateCategoriesOrderRequest;
}

export interface CategoryUpdateRefillValuesPutRequest {
    updateCategoriesRefillValueRequest: UpdateCategoriesRefillValueRequest;
}

/**
 * 
 */
export class CategoryApi extends runtime.BaseAPI {

    /**
     */
    async categoryCreatePostRaw(requestParameters: CategoryCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CategoryModel>> {
        if (requestParameters['createCategoryRequest'] == null) {
            throw new runtime.RequiredError(
                'createCategoryRequest',
                'Required parameter "createCategoryRequest" was null or undefined when calling categoryCreatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/Category/Create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCategoryRequestToJSON(requestParameters['createCategoryRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CategoryModelFromJSON(jsonValue));
    }

    /**
     */
    async categoryCreatePost(requestParameters: CategoryCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CategoryModel> {
        const response = await this.categoryCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async categoryDeleteIdDeleteRaw(requestParameters: CategoryDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling categoryDeleteIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/Category/Delete/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async categoryDeleteIdDelete(requestParameters: CategoryDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.categoryDeleteIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async categoryForAccountAccountIdGetRaw(requestParameters: CategoryForAccountAccountIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CategoryModel>>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling categoryForAccountAccountIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/Category/ForAccount/{accountId}`;
        urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CategoryModelFromJSON));
    }

    /**
     */
    async categoryForAccountAccountIdGet(requestParameters: CategoryForAccountAccountIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CategoryModel>> {
        const response = await this.categoryForAccountAccountIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async categoryUpdateIdPutRaw(requestParameters: CategoryUpdateIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CategoryModel>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling categoryUpdateIdPut().'
            );
        }

        if (requestParameters['updateCategoryRequest'] == null) {
            throw new runtime.RequiredError(
                'updateCategoryRequest',
                'Required parameter "updateCategoryRequest" was null or undefined when calling categoryUpdateIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/Category/Update/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCategoryRequestToJSON(requestParameters['updateCategoryRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CategoryModelFromJSON(jsonValue));
    }

    /**
     */
    async categoryUpdateIdPut(requestParameters: CategoryUpdateIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CategoryModel> {
        const response = await this.categoryUpdateIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async categoryUpdateOrderPutRaw(requestParameters: CategoryUpdateOrderPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CategoryModel>>> {
        if (requestParameters['updateCategoriesOrderRequest'] == null) {
            throw new runtime.RequiredError(
                'updateCategoriesOrderRequest',
                'Required parameter "updateCategoriesOrderRequest" was null or undefined when calling categoryUpdateOrderPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/Category/UpdateOrder`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCategoriesOrderRequestToJSON(requestParameters['updateCategoriesOrderRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CategoryModelFromJSON));
    }

    /**
     */
    async categoryUpdateOrderPut(requestParameters: CategoryUpdateOrderPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CategoryModel>> {
        const response = await this.categoryUpdateOrderPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async categoryUpdateRefillValuesPutRaw(requestParameters: CategoryUpdateRefillValuesPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CategoryModel>>> {
        if (requestParameters['updateCategoriesRefillValueRequest'] == null) {
            throw new runtime.RequiredError(
                'updateCategoriesRefillValueRequest',
                'Required parameter "updateCategoriesRefillValueRequest" was null or undefined when calling categoryUpdateRefillValuesPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/Category/UpdateRefillValues`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCategoriesRefillValueRequestToJSON(requestParameters['updateCategoriesRefillValueRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CategoryModelFromJSON));
    }

    /**
     */
    async categoryUpdateRefillValuesPut(requestParameters: CategoryUpdateRefillValuesPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CategoryModel>> {
        const response = await this.categoryUpdateRefillValuesPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
