/* tslint:disable */
/* eslint-disable */
/**
 * Schmeconomics.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategoryRefillValueUpdate
 */
export interface CategoryRefillValueUpdate {
    /**
     * 
     * @type {string}
     * @memberof CategoryRefillValueUpdate
     */
    categoryId: string;
    /**
     * 
     * @type {number}
     * @memberof CategoryRefillValueUpdate
     */
    refillValue: number;
}

/**
 * Check if a given object implements the CategoryRefillValueUpdate interface.
 */
export function instanceOfCategoryRefillValueUpdate(value: object): value is CategoryRefillValueUpdate {
    if (!('categoryId' in value) || value['categoryId'] === undefined) return false;
    if (!('refillValue' in value) || value['refillValue'] === undefined) return false;
    return true;
}

export function CategoryRefillValueUpdateFromJSON(json: any): CategoryRefillValueUpdate {
    return CategoryRefillValueUpdateFromJSONTyped(json, false);
}

export function CategoryRefillValueUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryRefillValueUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'categoryId': json['categoryId'],
        'refillValue': json['refillValue'],
    };
}

export function CategoryRefillValueUpdateToJSON(json: any): CategoryRefillValueUpdate {
    return CategoryRefillValueUpdateToJSONTyped(json, false);
}

export function CategoryRefillValueUpdateToJSONTyped(value?: CategoryRefillValueUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'categoryId': value['categoryId'],
        'refillValue': value['refillValue'],
    };
}

