/* tslint:disable */
/* eslint-disable */
/**
 * Schmeconomics.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategoryModel
 */
export interface CategoryModel {
    /**
     * 
     * @type {string}
     * @memberof CategoryModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryModel
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof CategoryModel
     */
    balance: number;
    /**
     * 
     * @type {number}
     * @memberof CategoryModel
     */
    refillValue: number;
    /**
     * 
     * @type {number}
     * @memberof CategoryModel
     */
    order: number;
}

/**
 * Check if a given object implements the CategoryModel interface.
 */
export function instanceOfCategoryModel(value: object): value is CategoryModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('balance' in value) || value['balance'] === undefined) return false;
    if (!('refillValue' in value) || value['refillValue'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    return true;
}

export function CategoryModelFromJSON(json: any): CategoryModel {
    return CategoryModelFromJSONTyped(json, false);
}

export function CategoryModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'balance': json['balance'],
        'refillValue': json['refillValue'],
        'order': json['order'],
    };
}

export function CategoryModelToJSON(json: any): CategoryModel {
    return CategoryModelToJSONTyped(json, false);
}

export function CategoryModelToJSONTyped(value?: CategoryModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'balance': value['balance'],
        'refillValue': value['refillValue'],
        'order': value['order'],
    };
}

