/* tslint:disable */
/* eslint-disable */
/**
 * Schmeconomics.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCategoryRequest
 */
export interface CreateCategoryRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateCategoryRequest
     */
    accountId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCategoryRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof CreateCategoryRequest
     */
    balance: number;
    /**
     * 
     * @type {number}
     * @memberof CreateCategoryRequest
     */
    refillValue: number;
}

/**
 * Check if a given object implements the CreateCategoryRequest interface.
 */
export function instanceOfCreateCategoryRequest(value: object): value is CreateCategoryRequest {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('balance' in value) || value['balance'] === undefined) return false;
    if (!('refillValue' in value) || value['refillValue'] === undefined) return false;
    return true;
}

export function CreateCategoryRequestFromJSON(json: any): CreateCategoryRequest {
    return CreateCategoryRequestFromJSONTyped(json, false);
}

export function CreateCategoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCategoryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'name': json['name'],
        'balance': json['balance'],
        'refillValue': json['refillValue'],
    };
}

export function CreateCategoryRequestToJSON(json: any): CreateCategoryRequest {
    return CreateCategoryRequestToJSONTyped(json, false);
}

export function CreateCategoryRequestToJSONTyped(value?: CreateCategoryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'name': value['name'],
        'balance': value['balance'],
        'refillValue': value['refillValue'],
    };
}

