/* tslint:disable */
/* eslint-disable */
/**
 * Schmeconomics.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTransactionRequest
 */
export interface CreateTransactionRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateTransactionRequest
     */
    categoryId: string;
    /**
     * 
     * @type {number}
     * @memberof CreateTransactionRequest
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof CreateTransactionRequest
     */
    notes: string | null;
}

/**
 * Check if a given object implements the CreateTransactionRequest interface.
 */
export function instanceOfCreateTransactionRequest(value: object): value is CreateTransactionRequest {
    if (!('categoryId' in value) || value['categoryId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('notes' in value) || value['notes'] === undefined) return false;
    return true;
}

export function CreateTransactionRequestFromJSON(json: any): CreateTransactionRequest {
    return CreateTransactionRequestFromJSONTyped(json, false);
}

export function CreateTransactionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTransactionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'categoryId': json['categoryId'],
        'amount': json['amount'],
        'notes': json['notes'],
    };
}

export function CreateTransactionRequestToJSON(json: any): CreateTransactionRequest {
    return CreateTransactionRequestToJSONTyped(json, false);
}

export function CreateTransactionRequestToJSONTyped(value?: CreateTransactionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'categoryId': value['categoryId'],
        'amount': value['amount'],
        'notes': value['notes'],
    };
}

