/* tslint:disable */
/* eslint-disable */
/**
 * Schmeconomics.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserModel } from './UserModel';
import {
    UserModelFromJSON,
    UserModelFromJSONTyped,
    UserModelToJSON,
    UserModelToJSONTyped,
} from './UserModel';

/**
 * 
 * @export
 * @interface SignInModel
 */
export interface SignInModel {
    /**
     * 
     * @type {UserModel}
     * @memberof SignInModel
     */
    userModel: UserModel;
    /**
     * 
     * @type {string}
     * @memberof SignInModel
     */
    accessToken: string;
    /**
     * 
     * @type {Date}
     * @memberof SignInModel
     */
    expiresOnUtc: Date;
}

/**
 * Check if a given object implements the SignInModel interface.
 */
export function instanceOfSignInModel(value: object): value is SignInModel {
    if (!('userModel' in value) || value['userModel'] === undefined) return false;
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('expiresOnUtc' in value) || value['expiresOnUtc'] === undefined) return false;
    return true;
}

export function SignInModelFromJSON(json: any): SignInModel {
    return SignInModelFromJSONTyped(json, false);
}

export function SignInModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignInModel {
    if (json == null) {
        return json;
    }
    return {
        
        'userModel': UserModelFromJSON(json['userModel']),
        'accessToken': json['accessToken'],
        'expiresOnUtc': (new Date(json['expiresOnUtc'])),
    };
}

export function SignInModelToJSON(json: any): SignInModel {
    return SignInModelToJSONTyped(json, false);
}

export function SignInModelToJSONTyped(value?: SignInModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userModel': UserModelToJSON(value['userModel']),
        'accessToken': value['accessToken'],
        'expiresOnUtc': ((value['expiresOnUtc']).toISOString()),
    };
}

