/* tslint:disable */
/* eslint-disable */
/**
 * Schmeconomics.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToggleUserToAccountRequest
 */
export interface ToggleUserToAccountRequest {
    /**
     * 
     * @type {string}
     * @memberof ToggleUserToAccountRequest
     */
    accountId: string;
    /**
     * 
     * @type {string}
     * @memberof ToggleUserToAccountRequest
     */
    userId: string;
}

/**
 * Check if a given object implements the ToggleUserToAccountRequest interface.
 */
export function instanceOfToggleUserToAccountRequest(value: object): value is ToggleUserToAccountRequest {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function ToggleUserToAccountRequestFromJSON(json: any): ToggleUserToAccountRequest {
    return ToggleUserToAccountRequestFromJSONTyped(json, false);
}

export function ToggleUserToAccountRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToggleUserToAccountRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'userId': json['userId'],
    };
}

export function ToggleUserToAccountRequestToJSON(json: any): ToggleUserToAccountRequest {
    return ToggleUserToAccountRequestToJSONTyped(json, false);
}

export function ToggleUserToAccountRequestToJSONTyped(value?: ToggleUserToAccountRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'userId': value['userId'],
    };
}

