/* tslint:disable */
/* eslint-disable */
/**
 * Schmeconomics.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCategoriesOrderRequest
 */
export interface UpdateCategoriesOrderRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateCategoriesOrderRequest
     */
    accountId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateCategoriesOrderRequest
     */
    categoryIds: Array<string>;
}

/**
 * Check if a given object implements the UpdateCategoriesOrderRequest interface.
 */
export function instanceOfUpdateCategoriesOrderRequest(value: object): value is UpdateCategoriesOrderRequest {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('categoryIds' in value) || value['categoryIds'] === undefined) return false;
    return true;
}

export function UpdateCategoriesOrderRequestFromJSON(json: any): UpdateCategoriesOrderRequest {
    return UpdateCategoriesOrderRequestFromJSONTyped(json, false);
}

export function UpdateCategoriesOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCategoriesOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'categoryIds': json['categoryIds'],
    };
}

export function UpdateCategoriesOrderRequestToJSON(json: any): UpdateCategoriesOrderRequest {
    return UpdateCategoriesOrderRequestToJSONTyped(json, false);
}

export function UpdateCategoriesOrderRequestToJSONTyped(value?: UpdateCategoriesOrderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'categoryIds': value['categoryIds'],
    };
}

