/* tslint:disable */
/* eslint-disable */
/**
 * Schmeconomics.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTransactionRequest
 */
export interface UpdateTransactionRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateTransactionRequest
     */
    categoryId: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UpdateTransactionRequest
     */
    timestampUtc: Date | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateTransactionRequest
     */
    amount: number | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateTransactionRequest
     */
    notes: string | null;
}

/**
 * Check if a given object implements the UpdateTransactionRequest interface.
 */
export function instanceOfUpdateTransactionRequest(value: object): value is UpdateTransactionRequest {
    if (!('categoryId' in value) || value['categoryId'] === undefined) return false;
    if (!('timestampUtc' in value) || value['timestampUtc'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('notes' in value) || value['notes'] === undefined) return false;
    return true;
}

export function UpdateTransactionRequestFromJSON(json: any): UpdateTransactionRequest {
    return UpdateTransactionRequestFromJSONTyped(json, false);
}

export function UpdateTransactionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTransactionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'categoryId': json['categoryId'],
        'timestampUtc': (json['timestampUtc'] == null ? null : new Date(json['timestampUtc'])),
        'amount': json['amount'],
        'notes': json['notes'],
    };
}

export function UpdateTransactionRequestToJSON(json: any): UpdateTransactionRequest {
    return UpdateTransactionRequestToJSONTyped(json, false);
}

export function UpdateTransactionRequestToJSONTyped(value?: UpdateTransactionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'categoryId': value['categoryId'],
        'timestampUtc': ((value['timestampUtc'] as any).toISOString()),
        'amount': value['amount'],
        'notes': value['notes'],
    };
}

