/* tslint:disable */
/* eslint-disable */
/**
 * Schmeconomics.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryRefillValueUpdate } from './CategoryRefillValueUpdate';
import {
    CategoryRefillValueUpdateFromJSON,
    CategoryRefillValueUpdateFromJSONTyped,
    CategoryRefillValueUpdateToJSON,
    CategoryRefillValueUpdateToJSONTyped,
} from './CategoryRefillValueUpdate';

/**
 * 
 * @export
 * @interface UpdateCategoriesRefillValueRequest
 */
export interface UpdateCategoriesRefillValueRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateCategoriesRefillValueRequest
     */
    accountId: string;
    /**
     * 
     * @type {Array<CategoryRefillValueUpdate>}
     * @memberof UpdateCategoriesRefillValueRequest
     */
    refillValues: Array<CategoryRefillValueUpdate>;
}

/**
 * Check if a given object implements the UpdateCategoriesRefillValueRequest interface.
 */
export function instanceOfUpdateCategoriesRefillValueRequest(value: object): value is UpdateCategoriesRefillValueRequest {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('refillValues' in value) || value['refillValues'] === undefined) return false;
    return true;
}

export function UpdateCategoriesRefillValueRequestFromJSON(json: any): UpdateCategoriesRefillValueRequest {
    return UpdateCategoriesRefillValueRequestFromJSONTyped(json, false);
}

export function UpdateCategoriesRefillValueRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCategoriesRefillValueRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'refillValues': ((json['refillValues'] as Array<any>).map(CategoryRefillValueUpdateFromJSON)),
    };
}

export function UpdateCategoriesRefillValueRequestToJSON(json: any): UpdateCategoriesRefillValueRequest {
    return UpdateCategoriesRefillValueRequestToJSONTyped(json, false);
}

export function UpdateCategoriesRefillValueRequestToJSONTyped(value?: UpdateCategoriesRefillValueRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'refillValues': ((value['refillValues'] as Array<any>).map(CategoryRefillValueUpdateToJSON)),
    };
}

