/* tslint:disable */
/* eslint-disable */
/**
 * Schmeconomics.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCategoryRequest
 */
export interface UpdateCategoryRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateCategoryRequest
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateCategoryRequest
     */
    balance?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateCategoryRequest
     */
    refillValue?: number | null;
}

/**
 * Check if a given object implements the UpdateCategoryRequest interface.
 */
export function instanceOfUpdateCategoryRequest(value: object): value is UpdateCategoryRequest {
    return true;
}

export function UpdateCategoryRequestFromJSON(json: any): UpdateCategoryRequest {
    return UpdateCategoryRequestFromJSONTyped(json, false);
}

export function UpdateCategoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCategoryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'balance': json['balance'] == null ? undefined : json['balance'],
        'refillValue': json['refillValue'] == null ? undefined : json['refillValue'],
    };
}

export function UpdateCategoryRequestToJSON(json: any): UpdateCategoryRequest {
    return UpdateCategoryRequestToJSONTyped(json, false);
}

export function UpdateCategoryRequestToJSONTyped(value?: UpdateCategoryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'balance': value['balance'],
        'refillValue': value['refillValue'],
    };
}

