/* tslint:disable */
/* eslint-disable */
/**
 * Schmeconomics.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Role } from './Role';
import {
    RoleFromJSON,
    RoleFromJSONTyped,
    RoleToJSON,
    RoleToJSONTyped,
} from './Role';

/**
 * 
 * @export
 * @interface UserModel
 */
export interface UserModel {
    /**
     * 
     * @type {string}
     * @memberof UserModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserModel
     */
    name: string;
    /**
     * 
     * @type {Role}
     * @memberof UserModel
     */
    role: Role;
}



/**
 * Check if a given object implements the UserModel interface.
 */
export function instanceOfUserModel(value: object): value is UserModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function UserModelFromJSON(json: any): UserModel {
    return UserModelFromJSONTyped(json, false);
}

export function UserModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'role': RoleFromJSON(json['role']),
    };
}

export function UserModelToJSON(json: any): UserModel {
    return UserModelToJSONTyped(json, false);
}

export function UserModelToJSONTyped(value?: UserModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'role': RoleToJSON(value['role']),
    };
}

