/**
 * Schmeconomics.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserModel } from './userModel';


export interface AuthModel { 
    user: UserModel;
    accessToken: string;
    refreshToken: string;
    expiresOnUtc: string;
}

