/**
 * Schmeconomics.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const Role = {
    User: 'User',
    Admin: 'Admin'
} as const;
export type Role = typeof Role[keyof typeof Role];

