/**
 * Schmeconomics.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoryRefillValueUpdate } from './categoryRefillValueUpdate';


export interface UpdateCategoriesRefillValueRequest { 
    accountId: string;
    refillValues: Array<CategoryRefillValueUpdate>;
}

