/**
 * Schmeconomics.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';


export interface UserModel { 
    id: string;
    name: string;
    role: Role;
}
export namespace UserModel {
}


